user/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import password_change, password_change_done, \
                                      password_reset, password_reset_done, \
                                      password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^$', views.render_main_page, name="render_main"),
    url(r'^login/$', views.user_login, name="login"),
    # url(r'^login/(?P<auth_status>[\w]+)/$', views.user_login, name="login_again"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^registration/$', views.user_register, name="register"),
    url(r'^need-login/$', views.need_login, name="need_login"),
    url(r'^user/(?P<user_id>\d+)/$', views.user_page, name="user_page"),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.edit_user_page, name="edit_user_page"),
]

verse/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.verse_list, name="verse_list"),
    url(r'^(?P<author_slug>[-\w]+)/$', views.verse_list, name="verse_list_by_author"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/$', views.verse_detail, name="verse_detail"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/add-comment/$', views.verse_comment, name="verse_comment"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/like/$', views.verse_like, name="verse_like"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/send-email/$', views.send_verse_by_email, name="send_verse_by_email"),
]

verses/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include("user.urls", namespace="user")),
    url(r'^verses/', include("verse.urls", namespace="verse")),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include("author.urls", namespace="author")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="profile", verbose_name = "Пользователь")
    date_of_birth = models.DateField(blank=True, null=True, verbose_name = "Дата рождения")
    GENDER_CHOICES = (("М", "Мужской"), ("Ж", "Женский"))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name = 'Пол',
                              null=True, blank=True)
    isadmin = models.BooleanField(default=False, verbose_name = "Права администратора")
    photo = models.ImageField(upload_to="users/%Y/%m/%d", blank=True, verbose_name = "Фотография")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name = "Дата создания профиля")
    updated_date = models.DateTimeField(auto_now=True, verbose_name = "Дата последнего изменения профиля")

    def __str__(self):
        return "Profile for user {}".format(self.user.username)

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

# import datetime  # datetime.datetime.now()
# from .models import Person

class LoginForm(forms.Form):
    username = forms.CharField(max_length = 30, label = "Логин")
    password = forms.CharField(max_length = 30, widget=forms.PasswordInput , label = "Пароль")
    rememberme = forms.BooleanField(required=False)


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(max_length = 30,
                               label = "Введите пароль",
                               widget = forms.PasswordInput)
    password2 = forms.CharField(max_length = 30,
                                label = "Введите пароль повторно",
                                widget = forms.PasswordInput)
    first_name = forms.CharField(max_length = 30, required = False, label = "Имя")
    last_name = forms.CharField(max_length = 30, required = False, label = "Фамилия")
    date_of_birth = forms.DateField(required = False, label = "Дата рождения",
                                    input_formats=['%d.%m.%Y',],
                                    widget=forms.DateInput(format = '%d.%m.%Y'),
                                    help_text = 'Введите дату в формате "дд.мм.гггг"')
    GENDER_CHOICES = (("М", "Мужской"), ("Ж", "Женский"))
    gender = forms.CharField(required = False, max_length = 1, label = "Пол", widget=forms.Select(choices = GENDER_CHOICES))
    photo = forms.ImageField(required = False, label = "Фотография")

    class Meta:
        model = User
        fields = ('username', 'email')
        labels = {
            'username': _("Логин"),
            'email': _('Email')
        }
        help_texts = {
            'username': _(""),
            'email': _('Например: user@mail.com'),
        }

    def clean_username(self):
        try:
            user = User.objects.get(username = self.cleaned_data["username"])
        except User.DoesNotExist:
            return self.cleaned_data["username"]
        raise forms.ValidationError('Аккаунт с таким именем уже существует')

    def clean_email(self):
        try:
            user = User.objects.get(email = self.cleaned_data["email"])
        except User.DoesNotExist:
            return self.cleaned_data["email"]
        raise forms.ValidationError('На данный email уже заведён аккаунт')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] == cd['password2']:
            return cd["password2"]
        else:
            raise forms.ValidationError("Пароли не соответствуют друг другу")

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.date_of_birth = self.cleaned_data["date_of_birth"]
        user.gender = self.cleaned_data["gender"]
        user.photo = self.cleaned_data["photo"]

        if commit:
            user.save()
        return user


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', )
        labels = {
            'first_name': _("Имя"),
            'last_name': _("Фамилия"),
            'email': _('Email'),
        }


class ProfileEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(required = False, label = "Дата рождения",
                                    input_formats=['%d.%m.%Y',],
                                    widget=forms.DateInput(format = '%d.%m.%Y'),
                                    help_text = 'Введите дату в формате "дд.мм.гггг"')
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'gender', 'photo', )

user/views.py
from django.shortcuts import render, get_object_or_404
# from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from author.models import Author
from .models import User, Profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# from django.forms.models import inlineformset_factory

authors = Author.objects.all()

# Create your views here.
def render_main_page(request):
    return render(request, "main.html", {"authors": authors,
                                         "section": "main_page"})


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request, user) # set the user in the session
                    request.session["username"] = user.username
                    request.session["user_id"] = user.id
                    request.session["user_email"] = user.email
                    request.session["user_is_staff"] = user.is_staff
                    return HttpResponseRedirect('/users/') # Authenticated successfully
                else:
                    # url = reverse('user:login_again', args=["disabled"])
                    # return HttpResponseRedirect(url) # Disabled account
                    auth_status = "disabled"
            else:
                # url = reverse('user:login_again', args=["invalid"])
                # return HttpResponseRedirect(url) # Invalid credentials
                auth_status = "invalid"
    else:
        auth_status = ""
        form = LoginForm()
    return render(request, "registration/login.html", {"authors": authors,
                                                       "form": form,
                                                       "auth_status": auth_status})


def user_logout(request):
    logout(request)
    messages.info(request, "Вы вышли из аккаунта")
    # return render(request, "registration/logged_out.html", {"authors": authors})
    return render(request, "main.html", {"authors": authors,
                                         "section": "main_page"})

def need_login(request):
    return render(request, "registration/need_login.html", {"authors": authors})

def user_register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST, request.FILES)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yer
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data["password1"])
            # Save the User object
            new_user.save()
            new_profile = Profile.objects.create(user = new_user,
                                                 date_of_birth = user_form.cleaned_data["date_of_birth"],
                                                 gender = user_form.cleaned_data["gender"])

            if request.FILES.get("photo", False):
                new_profile.photo = request.FILES["photo"]
            new_profile.save()
            return render(request, "registration/registration_done.html", {"authors": authors})
    else:
        user_form = UserRegistrationForm()
    return render(request, "registration/registration.html", {"form": user_form,
                                                              "authors": authors,
                                                              "section": "registration"})

@login_required
def user_page(request, user_id):
    user = get_object_or_404(User, id=user_id)
    profile = get_object_or_404(Profile, user = user)
    return render(request, "users/user/user_page.html", {"profile": profile,
                                                         "authors": authors,
                                                         "section": "user_page"})

@login_required
def edit_user_page(request, user_id):
    # user_id is not used for now
    if request.method == "POST":
        user_form = UserEditForm(instance = request.user, data = request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data = request.POST,
                                       files = request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Данные пользователя {} успешно изменены".format(request.user))
    else:
        user_form = UserEditForm(instance = request.user)
        profile_form = ProfileEditForm(instance = request.user.profile)
    return render(request,
                 "users/user/edit_user_page.html",
                 {"authors": authors,
                  "section": "user_page",
                  "user_form": user_form,
                  "profile_form": profile_form})

user/templates/users/user/edit_user_page.html
{% extends "main.html" %}

{% block title %}Редактирование данных аккаунта{% endblock %}

<!-- write jquery listener on field status -->

{% block first %}
    <div id="registration">
      <h2><strong>Редактирование аккаунта</strong></h2>
      <br>
      <form action="." method="post" enctype="multipart/form-data" class="form-horizontal">
        {% for field in user_form %}
            <div class="row">
              <div class="form-group {% if field.errors %}has-error{% endif %}">
                {% with field.name as name %}
                  <label for="{{ name }}" class="col-sm-2 control-label">{{ field.label }}</label>
                  <div class="col-sm-3">
                  <input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ name }}" value="{{ field.value }}"/>
                  {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                  {% endfor %}
                  </div>
                {% endwith %}
              </div>
            </div>
        {% endfor %}
        {% for field in profile_form %}
            <div class="row">
              <div class="form-group {% if field.errors %}has-error{% endif %}">
                {% with field.name as name %}
                  <label for="{{ name }}" class="col-sm-2 control-label">{{ field.label }}</label>
                  <div class="col-sm-3">
                      {% if name == "gender" %}
                        <select class="form-control" id="{{ field.id_for_label }}" maxlength="1" name="{{ name }}">
                          <option value="М">Мужской</option>
                          <option value="Ж">Женский</option>
                        </select>
                      {% elif name == "photo" %}
                        <input type="file" class="form-control" id="{{ field.id_for_label }}" name="{{ name }}"/>
                      {% elif name == "date_of_birth" %}
                        <input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ name }}" value="{{ field.value|date:'d.m.Y' }}"/>
                      {% else %}
                        <input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ name }}" value="{{ field.value }}"/>
                      {% endif %}
                      {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                      {% endfor %}
                  </div>
                {% endwith %}
              </div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <a class="btn btn-danger" href="{% url 'user:user_page' request.session.user_id %}" role="button">
          &emsp;Назад&emsp;
        </a>
        &emsp;
        <button type="submit" class="btn btn-default">Сохранить изменения</button>

      </form>
    </div>



{% endblock %}

user/templates/users/user/user_page.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ profile.user.username }}{% endblock %}

{% block content %}
  <div id="user-page">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>
          <strong>Моя страница</strong>
        </h2>
        <strong><a href="{% url 'user:edit_user_page' profile.user.id %}" class='edit-link'>редактировать <span class="glyphicon glyphicon-edit"></span></a></strong>

      </div><!-- end col-md-12-->
    </div><!-- end row-->
    <div class="row">
      <div class="col-md-3">
        {% load thumbnail %}
        {% thumbnail profile.photo "200x200" crop="center" as im %}
          <a href="{{ profile.photo.url }}">
            <img src="{% if im %}{{ im.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="Фото пользователя" class="img-thumbnail"/>
          </a>
        {% endthumbnail %}
      </div><!--End col-md-3 -->
      <div class="col-md-4">
        <p>
          <strong class="text-uppercase">Имя: </strong>{{ profile.user.first_name }}
        </p>
        <p>
          <strong class="text-uppercase">Фамилия: </strong>{{ profile.user.last_name }}
        </p>
        <p>
          <strong class="text-uppercase">Логин: </strong>{{ profile.user.username }}
        </p>
        <p>
          <strong class="text-uppercase">Email: </strong>{{ profile.user.email }}
        </p>
        <p>
          <strong class="text-uppercase">Дата рождения: </strong>{{ profile.date_of_birth|date:"d.m.Y" }}
        </p>
        <p>
          <strong class="text-uppercase">Пол: </strong>{{ profile.get_gender_display }}
        </p>
      </div>
    </div><!--End row-->
    <div class="row">
      <div class="col-md-12" id="verses_liked">
        <h3 class="text-center" style="color: #133463;">Понравившиеся произведения</h3>
        <ul>
          {% for verse_liked in request.user.verses_liked.all %}
            <li><a href="{% url 'verse:verse_detail' verse_liked.id verse_liked.slug %}" class="verse-link" style="color: #133463;">{{ verse_liked }}</a></li>
          {% empty %}
            <li>Нет понравившихся произведений</li>
          {% endfor %}
        </ul>
      </div>

    </div>
  </div><!-- end user-page-->
{% endblock %}