author/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<author_id>\d+)/(?P<author_slug>[-\w]+)/$', views.author_detail, name="author_detail"),
]

user/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import password_change, password_change_done, \
                                      password_reset, password_reset_done, \
                                      password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^$', views.render_main_page, name="render_main"),
    url(r'^login/$', views.user_login, name="login"),
    # url(r'^login/(?P<auth_status>[\w]+)/$', views.user_login, name="login_again"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^registration/$', views.user_register, name="register"),
    url(r'^need-login/$', views.need_login, name="need_login"),
    url(r'^user/(?P<user_id>\d+)/$', views.user_page, name="user_page"),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.edit_user_page, name="edit_user_page"),
]

verse/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.verse_list, name="verse_list"),
    url(r'^(?P<author_slug>[-\w]+)/$', views.verse_list, name="verse_list_by_author"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/$', views.verse_detail, name="verse_detail"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/add-comment/$', views.verse_comment, name="verse_comment"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/like/$', views.verse_like, name="verse_like"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/send-email/$', views.send_verse_by_email, name="send_verse_by_email"),
]

verses/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include("user.urls", namespace="user")),
    url(r'^verses/', include("verse.urls", namespace="verse")),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include("author.urls", namespace="author")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

verse/models.py
from django.db import models
from django.core.validators import RegexValidator
# from django.template.defaultfilters import slugify
from author.models import Author
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings

# Create your models here.
class Verse(models.Model):
    title = models.CharField(max_length = 150, verbose_name = "Заголовок")
    author = models.ForeignKey(Author, related_name = "verses", verbose_name = "Автор")
    year_of_writing = models.CharField(max_length = 200, blank = True, verbose_name = "Год написания",
                                        validators = [
                                            RegexValidator(
                                                regex = r'^\d{4}$',
                                                message = "You must enter a year",
                                                code = "Invalid year"
                                            )
                                        ])
    slug = models.SlugField(max_length = 50, db_index = True, unique = True, verbose_name='Идентификатор')
    text = models.TextField(blank = True, verbose_name = "Текст произведения")
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="verses_liked", blank = True, verbose_name = "Понравилось пользователям" )
    created_date = models.DateTimeField(auto_now_add = True, verbose_name = "Дата создания")
    update_date = models.DateTimeField(auto_now = True, verbose_name = "Дата обновления")


    class Meta:
        verbose_name = "Произведение"
        verbose_name_plural = "Произведения"

    # def save(self, *args, **kwargs):
    #     # self.slug = slugify("{} {}".format(self.title, self.author))
    #     self.slug = slugify(self.title)
    #     super(Verse, self).save(*args, **kwargs)

    def __str__(self):
        return "{} ({}. {})".format(self.title, self.author.first_name[0], self.author.surname)

    def get_absolute_url_detail(self):
        return reverse("verse:verse_detail", args=[self.id, self.slug])

verse/views.py
from django.shortcuts import render, get_object_or_404
from .models import Verse
from author.models import Author
from comment.models import Comment
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from comment.forms import CommentModelForm
from django.views.decorators.http import require_POST
from django.contrib import messages
# Create your views here.

authors = Author.objects.all()

def verse_list(request, author_slug=None):
    author = None
    # section = "main"
    verses = Verse.objects.all()
    section = "verse_list"
    if author_slug:
        author = get_object_or_404(Author, slug = author_slug)
        verses = verses.filter(author = author)
        section = "verse_list_by_author"
    return render(request, "verse/list.html", {"author": author,
                                               "authors": authors,
                                               "verses": verses,
                                               "section": section})

def verse_detail(request, verse_id, verse_slug):
    verse = get_object_or_404(Verse,
                              id = verse_id,
                              slug = verse_slug)
    # handles even with verses that do not contain comments
    comments = Comment.objects.filter(verse=verse, active=True)
    return render(request, "verse/detail.html", {"author": verse.author,
                                                 "authors": authors,
                                                 "verse": verse,
                                                 "comments": comments})

@login_required
@require_POST
def verse_comment(request, verse_id, verse_slug):
    text = request.POST["text"]
    verse = get_object_or_404(Verse, id=verse_id, slug=verse_slug)
    user = get_object_or_404(User, id=request.session["user_id"], username=request.session["username"])
    Comment.objects.create(verse = verse,
                           user = user,
                           text = text)
    messages.info(request, "Добавлен комментарий пользователем {}".format(user))
    return JsonResponse({"status": "comment added"})


@login_required
@require_POST
def verse_like(request, verse_id, verse_slug):
    verse = get_object_or_404(Verse, id=verse_id, slug=verse_slug)
    user = get_object_or_404(User, id=request.session["user_id"], username=request.session["username"])
    action = request.POST.get("action")
    if verse and action:
        try:
            if action == "like":
                verse.users_like.add(user)
                messages.info(request, 'Вам нравится произведение "{}"'.format(verse))
            else:
                verse.users_like.remove(user)
                messages.info(request, 'Вам больше не нравится произведение "{}"'.format(verse))
            return JsonResponse({"status": "ok"})
        except:
            pass
    return JsonResponse({"status": "not ok"})


@login_required
@require_POST
def send_verse_by_email(request, verse_id, verse_slug):
    """
    from django.core.mail import send_mail

    send_mail(
        'Subject here',
        'Here is the message.',
        'from@example.com',
        ['to@example.com'],
        fail_silently=False,
    )
    """
    user = User.objects.get(username = request.session["username"], id = request.session['user_id'])
    verse = Verse.objects.get(id = verse_id, slug = verse_slug)
    author = verse.author
    mail = send_mail("//Verses. {}".format(verse.title), verse.text, 'cestusss@gmail.com', [user.email,], fail_silently=False,)
    if mail:
        messages.success(request, "Письмо было успешно отрпавлено на {}".format(user.email))
        return JsonResponse({"status": "Email sent successfully"})
    else:
        messages.error(request, "Произошла ошибка при отправке письма!")
        return JsonResponse({"status": 'An error occured during email sending. Please, check email address and settings'})

verse/templates/verse/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ verse.title }}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      <div id="sidebar">
        <h3><strong>
          <a href="{% url 'author:author_detail' author.id author.slug %}" class="author-link">
            {{ author.first_name|first }}. {{ author.surname }}
          </a></strong>
        </h3>
        <ul class = "nav nav-pills nav-stacked">
          {% for v in author.verses.all %}
            <li role="presentation" {% if v.id == verse.id %}class="active"{% endif %}>
              <a href="{{ v.get_absolute_url_detail }}">
                {{ v.title }}{% if v.year_of_writing %} ({{ v.year_of_writing }}){% endif %}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div><!-- end sidebar -->
    </div><!-- End col-md-3-->
    <div class="col-md-6">
      <div id="main-verse">
        <h3 class="title">
          <a href="#collapseToolbar" id="show-menu" class="btn btn-default btn-sm" style="border-color: #365FB7;" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseToolbar">
            <span id="menu" class="glyphicon glyphicon-chevron-up"></span>
          </a>
          <strong>{{ verse.title }}</strong>&nbsp;
          <small>{{ verse.year_of_writing }}</small>
        </h3>
        <div class="collapse in" id="collapseToolbar">
          <div class="btn-toolbar" role="toolbar">
            <div class="btn-group" role="group">
              <a href = "#" class="btn btn-default btn-sm" data-toggle="modal" data-target="#verseModal">
                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&emsp;Читать
              </a>
            </div>
            {% if request.user.is_authenticated %}
              <div class="btn-group" role="group">
                <a href = "#' verse.id verse.slug %}" class="btn btn-default btn-sm" data-toggle="modal" data-target="#emailModal">
                  <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&emsp;Отправить на почту
                </a>
              </div>
              <div class="btn-group" role="group">
                <a href="#" class="btn btn-default btn-sm" data-toggle="modal" data-target="#commentModal">
                  <span class="glyphicon glyphicon-comment"></span>&emsp;Добавить комментарий
                </a>
              </div>
              <div class="btn-group" role="group" id="like-div">
                <form action="." method="post">
                  {% with verse.users_like.count as total_likes %}
                    <a href="#" class='btn btn-default btn-sm {% if request.user in verse.users_like.all %}un{% endif %}like-button' id="like-a"
                     data-action="{% if request.user in verse.users_like.all %}un{% endif %}like">
                      <span class="glyphicon glyphicon-heart"></span>&emsp;<span id="counter">{{ total_likes }}</span>
                    </a>
                  {% endwith %}
                  {% csrf_token %}
                </form>
              </div>
            {% else %}
              {% with verse.users_like.count as total_likes %}
                <a href='{% url "user:need_login" %}' class='btn btn-default btn-sm'>
                  <span class="glyphicon glyphicon-heart"></span>&emsp;<span id="counter">{{ total_likes }}</span>
                </a>
              {% endwith %}
            {% endif %}
          </div><!--end toolbar-->
        </div><!--end collapseToolbar-->
        <div class="content">
          <p>
            <div class="modal fade" id="verseModal" tabindex="-1" role="dialog" aria-labelledby="verseModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button><br>
                    <h4 class="modal-title text-center text-uppercase" id="verseModalLabel"><strong>{{ verse.title }}</strong><br><small>{{ verse.year_of_writing }}</small></h4>
                  </div><!--end modal-header-->
                  <div class="modal-body text-center">
                    {{ verse.text|linebreaks }}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                  </div>
                </div><!--end modal-content-->
              </div>
            </div><!-- end verseModalLabel-->
            <div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="emailModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button><br>
                    <h4 class="modal-title text-center text-uppercase" id="emailModalLabel"><strong>{{ verse.title }}</strong><br><small>{{ verse.year_of_writing }}</small></h4>
                  </div><!--end modal-header-->
                  <form action="." method="post">
                    {% csrf_token %}
                    <div class="modal-body text-center">
                      Данное произведение будет отправлено на Ваш Email <strong>{{ request.session.user_email }}</strong>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal">Отмена</button>
                      &emsp;
                      <a href = "{% url 'verse:send_verse_by_email' verse.id verse.slug %}" id="send_email" class="btn btn-default" data-dismiss="modal">Отправить</a>
                    </div>
                  </form>
                </div><!--end modal-content-->
              </div>
            </div><!-- end emailModalLabel-->
            {{ verse.text|linebreaks }}
          </p>
        </div><!-- end content-->
      </div><!-- end #main-verse-->
    </div><!--end col-md-6-->
    <div class="col-md-3">
      <div id="comments">
        <h3 class="title">
          <a href="#collapseComments" id="show-comments" class="btn btn-default btn-sm" style="border-color: #365FB7;" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseComments">
            <span id="comment" class="glyphicon glyphicon-chevron-up"></span>
          </a>
          <strong>Комментарии</strong>
        </h3>
        <div class="collapse in" id="collapseComments">
          {% for comment in comments %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <strong>{{ comment.user.username }}</strong>
                // {{ comment.update_date|date:"d.m.Y h:m:s" }}
              </div>
              <div class="panel-body">
                {{ comment.text|linebreaks }}
              </div>
            </div>
          {% empty %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <strong>Нет комментариев</strong>
              </div>
              <div class="panel-body">
                0 комментариев
              </div>
            </div>
          {% endfor %}
        </div><!-- end collapseComments-->

        <!-- comment modal form-->
        <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button><br>
                <h4 class="modal-title" id="commentModalLabel">
                  <strong>{{ verse.title }}</strong>&emsp;<small>{{ verse.year_of_writing }}</small>
                </h4>
              </div><!--end modal-header-->
              <form action="." method="post" id="postComment">
                <div class="modal-body">
                  <div class="form-group">
                    <label for="comment-area" class="control-label">Комментарий:</label>
                    <textarea class="form-control text-comment" id="id-comment-area" name="comment-area" maxlength="140"/></textarea>
                    {% csrf_token %}
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Закрыть</button>
                  &emsp;
                  <button type="submit" class="btn btn-default">Добавить комментарий</button>
                </div>
              </form>
            </div><!--end modal-content-->
          </div>
        </div><!-- end commentModalLabel-->
      </div>
    </div>
  </div><!--End row-->
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    $(document).ready(function(){
      $(document).on('submit', "#postComment", function(e){
        if ($('.text-comment').val()) {
          e.preventDefault();
          $.ajax({
            type: "POST",
            url: "/verses/{{ verse.id }}/{{ verse.slug }}/add-comment/",
            data: {
              text: $('.text-comment').val(),
              csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function(response){
              console.log(response["status"]);
              location.reload();
            }
          });
        } else {
          alert("Комментарий не может быть пустым");
        }
      });

      $(document).on('click', "a#send_email", function(e){
        e.preventDefault();
        $.ajax({
          type: 'POST',
          url: '/verses/{{ verse.id }}/{{ verse.slug }}/send-email/',
          data: {
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
          },
          success: function(response) {
            console.log(response["status"]);
            location.reload()
            // alert("Сообщение отправлено!");
          }
        });
      });

      $(document).on('click', "a#like-a", function(e){
        e.preventDefault();
        $.ajax({
          type: 'POST',
          url: '/verses/{{ verse.id }}/{{ verse.slug }}/like/',
          data: {
            action: $(this).data('action'),
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
          },
          cache: false,
          async: true,
          success: function(response) {
            if (response["status"] == 'ok')
            {
              var previous_action = $('a#like-a').data('action');
              //toggle data-action
              $('a#like-a').data('action', previous_action == 'like' ? 'unlike' : 'like');
              // update total likes
              var previous_likes = parseInt($('a#like-a span.counter').text());
              $('a#like-a span.counter').text(previous_action == "like" ? previous_likes + 1 : previous_likes - 1);
              console.log(response['status']);
              location.reload();
            }
            else {
              alert(response['status']);
            }
          }
        });
      });

      $('a#show-comments').click(function(){
        $("span#comment").toggleClass("glyphicon glyphicon-chevron-up comment");
        $("span#comment").toggleClass("glyphicon glyphicon-chevron-down comment");
      });
      $('a#show-menu').click(function(){
        $("span#menu").toggleClass("glyphicon glyphicon-chevron-up comment");
        $("span#menu").toggleClass("glyphicon glyphicon-chevron-down comment");
      });
    });
  </script>
{% endblock %}

verse/templates/verse/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if author %}{{ author.surname }}{% else %}Поэты{% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      <div id="sidebar">
        <div class="page-header">
          <h3><strong>Авторы</strong></h3>
        </div>
        <ul class = "nav nav-pills nav-stacked">
          <li role="presentation" {% if not author %}class="active"{% endif %}>
            <a href="{% url 'verse:verse_list' %}">Все авторы</a>
          </li>
          {% for a in authors %}
            <li role="presentation" {% if author.slug == a.slug %}class="active"{% endif %}>
              <a href="{{ a.get_absolute_url_list }}">
                {% with a.verses.count as num_verses %}
                  {{ a.surname }} <span class="badge">{{ num_verses }}</span>
                {% endwith %}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div><!-- end sidebar -->
    </div><!-- End col-md-3-->
    <div class="col-md-6">
      <div id="main-verses">
        <div class="page-header">
          <h3><strong>{% if author %}<a href="{% url 'author:author_detail' author.id author.slug %}" class="author-link">{{ author }}</a>
            {% else %}Все произведения{% endif %}</strong></h3>
        </div>
        {% if not author %}
          {% for a in authors %}
            <h4><strong><a href="{% url 'author:author_detail' a.id a.slug %}" class="author-link">{{ a }}</a></strong></h4>
            <ul>
              {% for v in a.verses.all %}
                <li>
                  <a href="{% url 'verse:verse_detail' v.id v.slug %}" class="verse-link">
                    {{ v.title }}
                  </a>
                </li>
              {% endfor %}
            </ul>
            <br>
          {% endfor %}
        {% else %}
          <ul>
            {% for v in verses %}
              <li><a href="{% url 'verse:verse_detail' v.id v.slug %}" class="verse-link">{{ v.title }}</a></li>
            {% endfor %}
          </ul>
        {% endif %}
      </div><!-- end #main-verses-->
    </div><!--end col-md-6-->
  </div><!--End row-->



{% endblock %}