author/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<author_id>\d+)/(?P<author_slug>[-\w]+)/$', views.author_detail, name="author_detail"),
]

user/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import password_change, password_change_done, \
                                      password_reset, password_reset_done, \
                                      password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^$', views.render_main_page, name="render_main"),
    url(r'^login/$', views.user_login, name="login"),
    # url(r'^login/(?P<auth_status>[\w]+)/$', views.user_login, name="login_again"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^registration/$', views.user_register, name="register"),
    url(r'^need-login/$', views.need_login, name="need_login"),
    url(r'^user/(?P<user_id>\d+)/$', views.user_page, name="user_page"),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.edit_user_page, name="edit_user_page"),
]

verse/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.verse_list, name="verse_list"),
    url(r'^(?P<author_slug>[-\w]+)/$', views.verse_list, name="verse_list_by_author"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/$', views.verse_detail, name="verse_detail"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/add-comment/$', views.verse_comment, name="verse_comment"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/like/$', views.verse_like, name="verse_like"),
    url(r'^(?P<verse_id>\d+)/(?P<verse_slug>[-\w]+)/send-email/$', views.send_verse_by_email, name="send_verse_by_email"),
]

verses/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include("user.urls", namespace="user")),
    url(r'^verses/', include("verse.urls", namespace="verse")),
    url(r'^admin/', admin.site.urls),
    url(r'^authors/', include("author.urls", namespace="author")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

verse/models.py
from django.db import models
from django.core.validators import RegexValidator
# from django.template.defaultfilters import slugify
from author.models import Author
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings

# Create your models here.
class Verse(models.Model):
    title = models.CharField(max_length = 150, verbose_name = "Заголовок")
    author = models.ForeignKey(Author, related_name = "verses", verbose_name = "Автор")
    year_of_writing = models.CharField(max_length = 200, blank = True, verbose_name = "Год написания",
                                        validators = [
                                            RegexValidator(
                                                regex = r'^\d{4}$',
                                                message = "You must enter a year",
                                                code = "Invalid year"
                                            )
                                        ])
    slug = models.SlugField(max_length = 50, db_index = True, unique = True, verbose_name='Идентификатор')
    text = models.TextField(blank = True, verbose_name = "Текст произведения")
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="verses_liked", blank = True, verbose_name = "Понравилось пользователям" )
    created_date = models.DateTimeField(auto_now_add = True, verbose_name = "Дата создания")
    update_date = models.DateTimeField(auto_now = True, verbose_name = "Дата обновления")


    class Meta:
        verbose_name = "Произведение"
        verbose_name_plural = "Произведения"

    # def save(self, *args, **kwargs):
    #     # self.slug = slugify("{} {}".format(self.title, self.author))
    #     self.slug = slugify(self.title)
    #     super(Verse, self).save(*args, **kwargs)

    def __str__(self):
        return "{} ({}. {})".format(self.title, self.author.first_name[0], self.author.surname)

    def get_absolute_url_detail(self):
        return reverse("verse:verse_detail", args=[self.id, self.slug])

verse/views.py
from django.shortcuts import render, get_object_or_404
from .models import Verse
from author.models import Author
from comment.models import Comment
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from comment.forms import CommentModelForm
from django.views.decorators.http import require_POST
from django.contrib import messages
# Create your views here.

authors = Author.objects.all()

def verse_list(request, author_slug=None):
    author = None
    # section = "main"
    verses = Verse.objects.all()
    section = "verse_list"
    if author_slug:
        author = get_object_or_404(Author, slug = author_slug)
        verses = verses.filter(author = author)
        section = "verse_list_by_author"
    return render(request, "verse/list.html", {"author": author,
                                               "authors": authors,
                                               "verses": verses,
                                               "section": section})

def verse_detail(request, verse_id, verse_slug):
    verse = get_object_or_404(Verse,
                              id = verse_id,
                              slug = verse_slug)
    # handles even with verses that do not contain comments
    comments = Comment.objects.filter(verse=verse, active=True)
    return render(request, "verse/detail.html", {"author": verse.author,
                                                 "authors": authors,
                                                 "verse": verse,
                                                 "comments": comments})

@login_required
@require_POST
def verse_comment(request, verse_id, verse_slug):
    text = request.POST["text"]
    verse = get_object_or_404(Verse, id=verse_id, slug=verse_slug)
    user = get_object_or_404(User, id=request.session["user_id"], username=request.session["username"])
    Comment.objects.create(verse = verse,
                           user = user,
                           text = text)
    messages.info(request, "Добавлен комментарий пользователем {}".format(user))
    return JsonResponse({"status": "comment added"})


@login_required
@require_POST
def verse_like(request, verse_id, verse_slug):
    verse = get_object_or_404(Verse, id=verse_id, slug=verse_slug)
    user = get_object_or_404(User, id=request.session["user_id"], username=request.session["username"])
    action = request.POST.get("action")
    if verse and action:
        try:
            if action == "like":
                verse.users_like.add(user)
                messages.info(request, 'Вам нравится произведение "{}"'.format(verse))
            else:
                verse.users_like.remove(user)
                messages.info(request, 'Вам больше не нравится произведение "{}"'.format(verse))
            return JsonResponse({"status": "ok"})
        except:
            pass
    return JsonResponse({"status": "not ok"})


@login_required
@require_POST
def send_verse_by_email(request, verse_id, verse_slug):
    """
    from django.core.mail import send_mail

    send_mail(
        'Subject here',
        'Here is the message.',
        'from@example.com',
        ['to@example.com'],
        fail_silently=False,
    )
    """
    user = User.objects.get(username = request.session["username"], id = request.session['user_id'])
    verse = Verse.objects.get(id = verse_id, slug = verse_slug)
    author = verse.author
    mail = send_mail("//Verses. {}".format(verse.title), verse.text, 'cestusss@gmail.com', [user.email,], fail_silently=False,)
    if mail:
        messages.success(request, "Письмо было успешно отрпавлено на {}".format(user.email))
        return JsonResponse({"status": "Email sent successfully"})
    else:
        messages.error(request, "Произошла ошибка при отправке письма!")
        return JsonResponse({"status": 'An error occured during email sending. Please, check email address and settings'})

verse/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <div id="wrapper">
      <!-- Navbar -->
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                  data-target = "#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <strong><a href="{% url 'user:render_main' %}" class="navbar-brand">//</a></strong>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li{% if section == "main_page" %} class="active"{% endif %}>
                    <a href="{% url 'user:render_main' %}">
                      <strong>
                        <span class="glyphicon glyphicon-home"></span> Главная
                      </strong>
                    </a>
                  </li>
                  <li{% if section == "verse_list" %} class="active"{% endif %}>
                    <a href="{% url 'verse:verse_list' %}">
                      <strong>
                        <span class="glyphicon glyphicon-list"></span> Все стихи
                      </strong>
                    </a>
                  </li>
                  <li class="dropdown {% if section == 'verse_list_by_author' %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                      aria-haspopup="true" aria-expanded="false">
                      <strong>
                        Стихи по авторам <span class="caret"></span>
                      </strong>
                    </a>
                    <ul class="dropdown-menu">
                      {% for a in authors %}
                        <li>
                          <a href="{% url 'verse:verse_list_by_author' a.slug %}">
                            {{ a }}
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </li><!--End Стихи -->
                  <li class="dropdown {% if section == 'author_list' %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                      aria-haspopup="true" aria-expanded="false">
                      <strong>
                        О поэтах <span class="caret"></span>
                      </strong>
                    </a>
                    <ul class="dropdown-menu">
                      {% for a in authors %}
                        <li>
                          <a href="{% url 'author:author_detail' a.id a.slug %}">
                            {{ a }}
                          </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </li><!-- End О Поэтах -->
                </ul><!-- end navbar=nav-->

                {% with request.session.username as name %}
                  {% if name %}
                    <ul class="nav navbar-nav navbar-right">
                      {% if request.session.user_is_staff %}
                        <li>
                          <a href="/admin/">
                            <strong><span class="glyphicon glyphicon-king"></span> Администрирование</strong>
                          </a>
                        </li>
                      {% endif %}
                      <li{% if section == 'user_page' %} class="active"{% endif %}>
                        <a href="{% url 'user:user_page' request.session.user_id %}">
                          <strong><span class="glyphicon glyphicon-user"></span> {{ name }}</strong>
                        </a>
                      </li>
                      <li>
                        <a href="{% url 'user:logout' %}"><strong><span class="glyphicon glyphicon-log-out"></span> Выйти</strong></a>
                      </li>
                    </ul>
                  {% else %}
                      <ul class="nav navbar-nav navbar-right">
                        <li>
                          <a href="{% url 'user:login' %}"><span class="glyphicon glyphicon-log-in"></span> <strong> Войти</strong></a>
                        </li>
                        <li{% if section == 'registration' %} class="active"{% endif %}>
                          <a href="{% url 'user:register' %}"><strong>Регистрация</strong></a>
                        </li>
                      </ul>
                  {% endif %}
                {% endwith %}

              </div>
            </div>
          </nav> <!-- End Navbar -->
        </div><!-- End col-md-12-->
      </div><!--end row-->

      <div id="content">
        <div class="row">
          <div class="col-md-12">
            {% if messages %}
              {% for message in messages %}
                {% with message.tags as tag %}
                  <div class="alert alert-{% if tag == 'error' %}danger{% elif tag == 'debug' %}info{% else %}{{ tag }}{% endif %} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong class="text-uppercase">{{ message.tags }}</strong> | {{ message|safe }}
                  </div>
                {% endwith %}
              {% endfor %}
            {% endif %}
          </div><!--end col-md-12-->
        </div><!--end row-->

        {% block content %}
        {% endblock %}
      </div>

    </div> <!-- end wrapper -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>